name: Solid - Build installer and create release

on:
  push:
    tags:
      - 'v*'  # Build an installer for commits that are tagged starting with 'v' e.g. v1.0

jobs:
  build-installer:
    name: Build Release And Make Installer
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Cache NuGet packages
        id: cache-nuget
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore src/solid.sln
      
      - name: Build
        run: dotnet build -c Release src/solid.sln --no-restore
      
      - name: List files and subdirectories
        run: |
          $path = "output"  # Change this to your target path
          Get-ChildItem -Path $path -Recurse
        shell: powershell

      - name: Build Installer
        run: iscc installer/setup.iss

      - uses: actions/upload-artifact@v4
        with:
          name: SolidInstaller.exe
          path: installer\Output\SolidInstaller.exe
          if-no-files-found: error

  sign-installer:
    name: Sign SOLID installer
    needs: build-installer
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: SolidInstaller.exe
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: SolidInstaller.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: SolidInstaller.exe
          body: |
            Release for version ${{ github.ref }}
          draft: true